"""add manga

Revision ID: cbe6e1a95184
Revises: bdf2a894ddb5
Create Date: 2025-01-11 04:34:25.172411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe6e1a95184'
down_revision: Union[str, None] = 'bdf2a894ddb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mangas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assoc_manga_genres',
    sa.Column('id_manga', sa.Uuid(), nullable=False),
    sa.Column('id_genre', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_genre'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['id_manga'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id_manga', 'id_genre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_manga_genres')
    op.drop_table('mangas')
    op.drop_table('genres')
    # ### end Alembic commands ###
