"""Rename app_token to access_token

Revision ID: d1583e66c807
Revises: cbe6e1a95184
Create Date: 2025-03-06 13:48:05.427335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1583e66c807'
down_revision: Union[str, None] = 'cbe6e1a95184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    op.drop_column('users', 'app_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
